# Generated by Django 5.2.4 on 2025-07-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='btech',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
