# Generated by Django 5.2.4 on 2025-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayapp', '0002_student_btech'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
