# Generated by Django 5.2.4 on 2025-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayapp', '0003_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='btech',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
